### ISSUE TITLE
Inclusion of baselines: pysparnn, annoy, faiss, hdidx

### ISSUE THREAD

**Issue by icarocd** [ejaasaari/mrpt-comparison#1]
Please, consider the inclusion of the following methods: pysparnn, annoy, and faiss, hdidx.
If some of them are not directly comparable, would you please clarify?

**Comment by kianho** [comment]
+1
I am also interested in seeing these additional comparisons

**Comment by ejaasaari** [comment]
Closing this as MRPT has been included in [ann-benchmarks](https://github.com/erikbern/ann-benchmarks) for a while now.

**Comment by icarocd** [comment]
@ejaasaari link does not work. Is it a private repository?

**Comment by ejaasaari** [comment]
@icarocd sorry, should be working now.
